logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        Type: TRACE
spring:
  application:
    name: ehealth-scheduling-system
  datasource:
    password: ehealthss
    url: jdbc:mysql://localhost:3306/ehealth_scheduling_system
    username: ehealthss
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    hibernate:
      ddl-auto: none
